### ISSUE TITLE
Code for CBAM

### ISSUE THREAD

**Issue by briannghiem** [Yonsei-MILab/MRI-Motion-Artifact-Correction-Self-Assisted-Priors#1]
Hello, thank you for making your code repo available! I'm interested in exploring your motion correction algorithm because of its efficient handling of 3D volumes and self-assisted priors. I noticed that your code for the attention blocks is missing (/main/Correction_Multi_input.py, line 8 ), could you please make it available?

**Comment by Yonsei-MILab** [comment]
Thank you for your interest in our work.

Based on your comment, we have added the implementation of CBAM function in the same file: 'Correction_Multi_input.py' within lines: 19~93.

Regards,

**Comment by Yonsei-MILab** [comment]
Thank you for your interest in our work.

Based on your comment, we have added the implementation of CBAM function in the same file: 'Correction_Multi_input.py' within lines: 19~93.

Regards,

**Comment by briannghiem** [comment]
Thank you!
